config/routes.rb
Rails.application.routes.draw do

  resources :statuses, except: [:new, :edit]

  scope 'admin' do
    resources :statuses, only: [:new, :edit]
    get '/statuses' => 'statuses#admin', as: :admin_status
  end

end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :index
  before_action :verify_admin, except: :index

  layout 'admin', except: ['index']
  # layout 'clean', only: ['index']

  # GET /statuses
  def index
    @page_title = "System Status"
    @title_tag = "#{Settings.site_name}: #{@page_title}"
    @meta_desc = "See the current status of #{Settings.site_name} systems here."
    @keywords = "System Status"

    add_breadcrumb "Status Board"
    @statuses = Status.all
  end

  def admin
    @statuses = Status.all
  end

  # GET /statuses/1
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  def create
    @status = Status.new(status_params)

    if @status.save
      redirect_to admin_status_path
    else
      render :new
    end
  end

  # PATCH/PUT /statuses/1
  def update
    if @status.update(status_params)
      redirect_to admin_status_path
    else
      render :edit
    end
  end

  # DELETE /statuses/1
  def destroy
    @status.destroy
    redirect_to admin_status_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def status_params
      params.require(:status).permit(:service, :description, :status, :active)
    end

    def verify_admin
      (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
    end




end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_admin.html.erb
<% status = admin %>
<tr>
  <td><span class="more-important"><%= status.service %></span>
    <br/><span class="less-important"><%= status.description %></span>
  </td>
  <td class="text-right"><%= status.status %></td>
  <td class="text-right">
    <div class="btn-group">
      <span id="row-<%= status.id %>" data-toggle="dropdown" aria-expanded="false" class='btn dropdown-toggle glyphicon glyphicon-align-justify'></span>
      <ul class="dropdown-menu dropdown-menu-right" role="menu" data-hook="admin_context_menu">
        <li><%= link_to t(:edit, default: 'Edit'), edit_status_path(status.id) %></li>
        <li><%= link_to t(:delete, default: 'Delete'), status, data: {confirm: t(:delete_confirm, default: 'Please confirm you really want to DELETE this')}, method: :delete, remote: true, class: 'less-important' %></li>
      </ul>
    </div>
  </td>
</tr>

app/views/statuses/_form.html.erb
<%= bootstrap_form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :service, class: 'form-control' %>
    <%= f.text_area :description, class: 'form-control'  %>
    <%= f.text_field :status, class: 'form-control'  %>
    <%= f.check_box :active, class: 'form-control'  %>
    <%= f.submit %>
<% end %>

app/views/statuses/_status.html.erb
<tr>
  <td><span class="more-important"><%= status.service %></span>
    <br/><span class="less-important"><%= status.description %></span>
  </td>
  <td class="text-right"><%= status.status %></td>
</tr>

app/views/statuses/_status_board.html.erb
<h2 class="text-center space-h2">System Status</h2>

<table id="forums" class="table-hover">
  <col>
  <col width="10%">

  <tr>
      <th>Service</th>
		  <th class="text-right">Status</th>
  </tr>

  <tbody>
	<%= render :partial => 'statuses/status', :collection => @statuses %>
  </tbody>
</table>

app/views/statuses/admin.html.erb
<h2>System Status <span class="admin-options pull-right">
  <%= link_to t(:new_status, default: "Add a System"), new_status_path, class: 'btn btn-primary' %>
</span></h2>

<table id="forums" class="table-hover">
  <col>
  <col width="10%">
  <col width="10%">

  <tr>
      <th>Service</th>
		  <th class="text-right">Status</th>
      <th></th>
  </tr>

  <tbody>
	<%= render :partial => 'statuses/admin', :collection => @statuses %>
  </tbody>
</table>

app/views/statuses/edit.html.erb
<h2>Editing System</h2>

<%= render 'form' %>

app/views/statuses/index.html.erb
<table id="forums" class="table-hover">
  <col>
  <col width="10%">

  <tr>
      <th>Service</th>
		  <th class="text-right">Status</th>
  </tr>

  <tbody>
	<%= render :partial => 'status', :collection => @statuses %>
  </tbody>
</table>

app/views/statuses/new.html.erb
<h2>Add a System</h2>

<%= render 'form' %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service:</strong>
  <%= @status.service %>
</p>

<p>
  <strong>Description:</strong>
  <%= @status.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @status.status %>
</p>

<p>
  <strong>Active:</strong>
  <%= @status.active %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>